name: sercl
description: Sercl Flutter App

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.1+2

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  json_annotation: 3.0.0
  image_picker: ^0.6.3+1
  firebase_messaging: 6.0.9
  connectivity: ^0.4.5+3
  load: 0.1.5+1
  rxdart: ^0.22.6
  sqflite: any
  path_provider: any
  url_launcher: ^5.1.2
  ndialog: ^2.0.2+1
  http_logger: 1.0.0
  photo_view: ^0.5.0
  rflutter_alert:
  carousel_slider: ^1.4.1
  flutter_datetime_picker: 1.3.8
  flutter_image_compress: ^0.6.3
  smooth_star_rating: 1.0.4+2
  #draggable_scrollbar: ^0.0.4
  #cupertino_icons: ^0.1.3
  email_validator: ^1.0.0
  dotted_border: ^1.0.3
  configurable_expansion_tile: ^1.0.0
  file_picker: 1.5.0+2
  fluttertoast: ^3.1.3
  auto_route: ^0.2.0+1
  google_sign_in: any
  get_it:
  datetime_picker_formfield: ^1.0.0
  shared_preferences: 0.5.7+1
  intl: ^0.16.0
  day_selector: ^1.0.0
  string_validator: ^0.1.3
  flutter_staggered_grid_view: ^0.3.0
  firebase_crashlytics: ^0.1.2+4
  flutter_localizations:
    sdk: flutter
  flutter_cupertino_localizations: 1.0.1
  firebase_database: 3.1.1
  bubble: 1.1.9+1
  flutter_downloader: ^1.4.1
  audioplayers: 0.14.0
  permission_handler: ^4.2.0+hotfix.3
  package_info: ^0.4.0+14
  video_player: ^0.10.8+1
  seekbar: ^0.0.2
  # keyboard_visibility: ^0.5.6
  duration: ^2.0.11
  flutter_audio_recorder: ^0.5.5
  google_maps_flutter: 0.5.25+2
  geocoder: ^0.2.1
  location: ^3.0.0
  flutter_rating_bar: 3.0.1+1
  toast: ^0.1.5
  flutter_html: 0.11.0
  #flutter_downloader: ^1.4.1
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.7.3
  auto_route_generator: any
  json_serializable: ^3.2.3
  build_runner: any

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/launcher/ic_launcher.png"
  adaptive_icon_foreground: "assets/launcher/ic_launcher.png"
  adaptive_icon_background: "#00ffffff"
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
